[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#51afef"
text = "CellBackground"

[font]
size = 10

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 5, y = 5 }
dynamic_padding = true
