[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"
